name: GitHub Action next2 flow to Docker hub 

on:
  push:
    branches: [main]

jobs:
  build-push-images:
    name: Budowa i publikacja obrazow na repozytorium
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Buildx set-up
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: przet
          password: da719a2a-116c-41db-8bd0-869711775eb5


      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2 
        with:
          context: ./
          platforms: linux/amd64,linux/s390x,linux/arm64
          file: ./dockerfile.v1
          push: true
          tags: przet/lab:lab6
          
